modLoader="kotlinforforge"
loaderVersion="[4,)"
license="CC0-1.0"
issueTrackerURL="https://github.com/Me/advanced-timer/issues"

[[mods]]
modId="advanced_timer"
version="${version}"
displayName="Advanced Timer"
authors="Me!"
description='''
This is an example description! Tell everyone what your mod is about!
'''

[[dependencies.advanced_timer]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.advanced_timer]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.11,)"
    ordering="NONE"
    side="CLIENT"
