modLoader="kotlinforforge"
loaderVersion="[6,)"
license="MIT"
issueTrackerURL="https://github.com/Me/advanced-timer/issues"

[[mods]]
modId="advanced_timer"
version="${version}"
displayName="Advanced Timer"
authors="L3-N0X"
description='''
Adds a timer with many features like placing it anywhere on the screen, changing its color, auto-pausing and more.
'''

[[dependencies.advanced_timer]]
    modId="neoforge"
    type="required"
    versionRange="[21.11,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.advanced_timer]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.11,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.advanced_timer]]
    modId="yet_another_config_lib_v3"
    type="required"
    versionRange="[3.8.2,)"
    ordering="NONE"
    side="BOTH"
